GestAgropInter/Controllers/AnimalController.cs
using GestAgropInter.Models;
using GestAgropInter.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace GestAgropInter.Controllers
{
    public class AnimalController : Controller
    {
        private readonly IAnimalRepository _animal;
        private readonly IFazendaRepository _fazenda;

        Animal ani = new Animal();
        public AnimalController(IAnimalRepository animal, IFazendaRepository fazenda)
        {
            _animal = animal;
            _fazenda = fazenda;
        }

        public IActionResult Index()
        {
            var animais = _animal.GetAllAnimal();

            return View(animais);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Animal animal = _animal.GetAnimal(id);

            if (animal == null)
            {
                return NotFound();
            }
            animal.FazendaList = _fazenda.GetAllFazenda();
            return View(animal);
        }


        [HttpGet]
        public IActionResult Create()
        {
            ani = new Animal();
            ani.FazendaList = _fazenda.GetAllFazenda();
            return View(ani);
        }
        [HttpGet]

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult CreateCadastro([Bind] Animal animal)
        {
        

            if (ModelState.IsValid)
            {
                if (animal.Id != null)
                {
                    animal.DataAlteracao = DateTime.Now;
                    _animal.UpdateAnimal(animal);
                }
                else
                    _animal.AddAnimal(animal);
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Animal animal = _animal.GetAnimal(id);
           

            if (animal == null)
            {
                return NotFound();
            }
            animal.FazendaList = _fazenda.GetAllFazenda();
            return View(animal);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind] Animal animal)
        {
            if (id != animal.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _animal.UpdateAnimal(animal);
                return RedirectToAction("Index");
            }
            return View(animal);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Animal animal = _animal.GetAnimal(id);

            if (animal == null)
            {
                return NotFound();
            }
            return View(animal);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? id)
        {
            _animal.DeleteAnimal(id);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        [HttpGet]
        public IActionResult VerificaTag(string tag)
        {

            if (tag == null)
            {
                return NotFound();
            }

            Animal animal = _animal.GetAnimal(tag);
            string mensagem = "yes";
            if (animal == null)
                mensagem = "not";
            return Ok(new
            {
                mensagem = mensagem
            });
        }

        [HttpPost]
        public IActionResult SalvarListaAnimais([FromBody] List<Animal> animais)
        {
            foreach (var animal in animais)
            {
                
                if (animal.Tag == "" || animal.Tag.Length < 15)
                    return Ok(new { erro = "true", message = "A tag informada é invalida!"});
                Animal exisAnimal = _animal.GetAnimal(animal.Tag);
                if (exisAnimal != null)
                    return Ok(new { erro = "true", message = "Já existe uma animal cadastrado com esse tag" });
            }
            try
            {
                _animal.AddAnimais(animais);
                return Ok(new { erro = "false", message = "Cadastro realizado com sucesso!!!" });
            }
            catch (Exception)
            {
                return BadRequest("Aconteceu algum erro!");
                throw;
            }
            
           
        }

    }
}

GestAgropInter/Controllers/ColetivoController.cs
using GestAgropInter.Models;
using GestAgropInter.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Data.OleDb;
using System.Data;
using System.Diagnostics;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Http;
using System.Formats.Asn1;
using System.Globalization;


namespace GestAgropInter.Controllers
{
    public class ColetivoController : Controller
    {
        private readonly IAnimalRepository _animal;
        private readonly IFazendaRepository _fazenda;
        private IHostingEnvironment Environment;
        private IConfiguration Configuration;
        Animal ani = new Animal();
        IWebHostEnvironment _appEnvironment;

        public ColetivoController(IAnimalRepository animal, IFazendaRepository fazenda, IHostingEnvironment _environment, IConfiguration _configuration, IWebHostEnvironment env)
        {
            _animal = animal;
            _fazenda = fazenda;
            Environment = _environment;
            Configuration = _configuration;
            _appEnvironment = env;
        }

        public IActionResult Index()
        {
            ViewBag.Fazenda = _fazenda.GetAllFazenda();
            return View();
        }
                

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpPost]
        public IActionResult ImportarArquivo(IFormFile postedFile)
        {
            if (postedFile != null)
            {


                string path = Path.Combine(_appEnvironment.WebRootPath, "Uploads");
                if (!Directory.Exists(path))
                {
                    Directory.CreateDirectory(path);
                }

                string fileName = Path.GetFileName(postedFile.FileName);
                string filePath = Path.Combine(path, fileName);
                using (FileStream stream = new FileStream(filePath, FileMode.Create))
                {
                    postedFile.CopyTo(stream);
                }

                string csvData = System.IO.File.ReadAllText(filePath);
                DataTable dt = new DataTable();
                bool firstRow = true;
                foreach (string row in csvData.Split('\n'))
                {
                    if (!string.IsNullOrEmpty(row))
                    {
                        if (!string.IsNullOrEmpty(row))
                        {
                            if (firstRow)
                            {
                                foreach (string cell in row.Split(';'))
                                {
                                    dt.Columns.Add(cell.Trim());
                                }
                                firstRow = false;
                            }
                            else
                            {
                                dt.Rows.Add();
                                int i = 0;
                                foreach (string cell in row.Split(';'))
                                {
                                    dt.Rows[dt.Rows.Count - 1][i] = cell.Trim();
                                    i++;
                                }
                            }
                        }
                    }
                }
                List<Animal> listaAnimais = new List<Animal>();
                foreach (DataRow dataRow in dt.Rows)
                {
                    if (dataRow["Fazenda"].ToString() != "")
                    {
                        Fazenda faze = _fazenda.GetFazenda(dataRow["Fazenda"].ToString());
                        if (faze == null)
                        {
                            faze = new Fazenda(dataRow["Fazenda"].ToString(), "Cadastrado pelo coletivo");
                            _fazenda.AddFazenda(faze);
                        }
                        string sexoAjustado = dataRow["Sexo"].ToString().StartsWith("F") ? "Fêmea" : dataRow["Sexo"].ToString();
                        Animal animal = new Animal(dataRow["Tag"].ToString(), sexoAjustado, (int)faze.Id);
                        listaAnimais.Add(animal);
                    }

                }

                if (listaAnimais.Count() > 0)
                    _animal.AddAnimais(listaAnimais);
            }
            return RedirectToAction("Index","Animal");
        }
    }
}

GestAgropInter/Controllers/FazendaController.cs
using GestAgropInter.Models;
using GestAgropInter.Models.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Diagnostics;

namespace GestAgropInter.Controllers
{
    public class FazendaController : Controller
    {
        private readonly IFazendaRepository _fazenda;


        public FazendaController(IFazendaRepository fazenda)
        {
            _fazenda = fazenda;
        }

        public IActionResult Index()
        {
            var fazendas = _fazenda.GetAllFazenda();
            return View(fazendas);
        }

        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Fazenda fazenda = _fazenda.GetFazenda(id);

            if (fazenda == null)
            {
                return NotFound();
            }
            return View(fazenda);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind] Fazenda fazenda)
        {

            if (ModelState.IsValid)
            {
                if (fazenda.Id != null)
                {
                    fazenda.DataAlteracao = DateTime.Now;
                    _fazenda.UpdateFazenda(fazenda);
                }                    
                else
                    _fazenda.AddFazenda(fazenda);
                return RedirectToAction("Index");
            }
            return View(fazenda);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Fazenda fazenda = _fazenda.GetFazenda(id);

            if (fazenda == null)
            {
                return NotFound();
            }
            return View(fazenda);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind] Fazenda fazenda)
        {
            if (id != fazenda.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                _fazenda.UpdateFazenda(fazenda);
                return RedirectToAction("Index");
            }
            return View(fazenda);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            Fazenda fazenda = _fazenda.GetFazenda(id);

            if (fazenda == null)
            {
                return NotFound();
            }
            return View(fazenda);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int? id)
        {
            _fazenda.DeleteFazenda(id);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [HttpGet]
        public IActionResult GetFazenda()
        {

            var fazenda = _fazenda.GetAllFazenda();
            return Ok(new
            {
                fazenda = fazenda
            });
        }
    }
}

GestAgropInter/Views/Shared/_Footer.cshtml
  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="float-right d-none d-sm-inline">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2022-2023 <a href="https://pecuariadealtaperformance.com.br/gestaoagropecuaria/">Gestão Agropecuária e Intergado </a>.</strong>Versão 1 All rights reserved.
  </footer>

GestAgropInter/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    @*<meta content="width=device-width, initial-scale=1.0" name="viewport">*@
    <title>@ViewData["Title"] - GestAgropInter</title>
      <!-- Google Font: Source Sans Pro -->
      <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
      <!-- Font Awesome Icons -->
      <link rel="stylesheet" href="~/adminlte/plugins/fontawesome-free/css/all.min.css">
      <!-- Theme style -->
      <link rel="stylesheet" href="~/adminlte/dist/css/adminlte.min.css">
    @await RenderSectionAsync("Styles", required: false)
    <script src="~/js/site.js"></script>
    <link rel="shortcut icon" type="image/x-icon" href="~/img/favicon.ico">
     <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.1.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
</head>
<body>

    <partial  name="_Navbar"/>
    <partial  name="_Sidebar"/>
    @RenderBody()
    <partial  name="_Footer"/>
    <!-- REQUIRED SCRIPTS -->

    <!-- jQuery -->
    <script src="~/adminlte/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/adminlte/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/adminlte/dist/js/adminlte.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

GestAgropInter/Views/Shared/_Navbar.cshtml
  <!-- Navbar -->
  <nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <!-- Left navbar links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
      </li>
    </ul>    
  </nav>
  <!-- /.navbar -->

GestAgropInter/Views/Shared/_Sidebar.cshtml
  <!-- Main Sidebar Container -->
  <aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="index3.html" class="brand-link">
      <img src="~/img/logo.png" alt="Gestão Agropecuária e Intergado" class="brand-image img-circle elevation-3" style="opacity: .8">
      <span class="brand-text font-weight-light">GestAgropInter</span>
    </a>

    <!-- Sidebar -->
    <div class="sidebar">
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
        <div class="image">
          <img src="~/adminlte/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
        </div>
        <div class="info">
          <a href="#" class="d-block">Marcos Ramos</a>
        </div>
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
           <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">                
              <i class="nav-icon fas fa-bars"></i>
              <p>
                Home               
              </p>
            </a>
          </li>
           <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Fazenda" asp-action="Index">
              <i class="nav-icon fa fa-map-marker"></i>
              <p>
                Fazenda               
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" asp-area="" asp-controller="Animal" asp-action="Index">
              <i class="nav-icon fa fa-plus-square"></i>
              <p>
                Cadastro Animal               
              </p>
            </a>
          </li>
          <li class="nav-item">
            <a  class="nav-link" asp-area="" asp-controller="Coletivo" asp-action="Index">
              <i class="nav-icon fa fa-plus-square"></i>                       
              <p>
                Cadastro coletivo               
              </p>
            </a>
          </li>
        </ul>
      </nav>
      <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
  </aside>